language: elixir
elixir: 1.0.4
otp_release:
  - 17.4
env:
  - WEBDRIVER=selenium

install:
  - mix local.hex --force
  - mix deps.get


before_script:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - bash $TRAVIS_BUILD_DIR/bin/start_webdriver.sh
  - cd $TRAVIS_BUILD_DIR/client
  - npm install
  - npm install bower
  - bower install
  - cd ../

script: mix test